[project]
name = "pdfbind"
version = "0.1.1"
description = ""
readme = "README.md"
license = "Apache-2.0" 
authors = [
    { name = "Sasha Ovsankin", email = "sasha@ovsankin.com" }
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "pikepdf>=9.2.1",
    "pyyaml>=6.0.2"
]

[project.scripts]
pdfbind = "pdfbind.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["pdfbind"]
